// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteKeysKeyIDCertificatesCertificateIDReader is a Reader for the DeleteKeysKeyIDCertificatesCertificateID structure.
type DeleteKeysKeyIDCertificatesCertificateIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteKeysKeyIDCertificatesCertificateIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteKeysKeyIDCertificatesCertificateIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteKeysKeyIDCertificatesCertificateIDNoContent creates a DeleteKeysKeyIDCertificatesCertificateIDNoContent with default headers values
func NewDeleteKeysKeyIDCertificatesCertificateIDNoContent() *DeleteKeysKeyIDCertificatesCertificateIDNoContent {
	return &DeleteKeysKeyIDCertificatesCertificateIDNoContent{}
}

/*DeleteKeysKeyIDCertificatesCertificateIDNoContent handles this case with default header values.

Certificate deleted
*/
type DeleteKeysKeyIDCertificatesCertificateIDNoContent struct {
}

func (o *DeleteKeysKeyIDCertificatesCertificateIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /keys/{key_id}/certificates/{certificate_id}][%d] deleteKeysKeyIdCertificatesCertificateIdNoContent ", 204)
}

func (o *DeleteKeysKeyIDCertificatesCertificateIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
