// Code generated by go-swagger; DO NOT EDIT.

package system

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/form3tech-oss/go-form3/models"
)

// NewPostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams creates a new PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams object
// with the default values initialized.
func NewPostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams() *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams {
	var ()
	return &PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParamsWithTimeout creates a new PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParamsWithTimeout(timeout time.Duration) *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams {
	var ()
	return &PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams{

		timeout: timeout,
	}
}

// NewPostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParamsWithContext creates a new PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParamsWithContext(ctx context.Context) *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams {
	var ()
	return &PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams{

		Context: ctx,
	}
}

// NewPostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParamsWithHTTPClient creates a new PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParamsWithHTTPClient(client *http.Client) *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams {
	var ()
	return &PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams{
		HTTPClient: client,
	}
}

/*PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams contains all the parameters to send to the API endpoint
for the post vocalinkreport certificate requests certificate request ID certificate operation typically these are written to a http.Request
*/
type PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams struct {

	/*CertificateCreationRequest*/
	CertificateCreationRequest *models.VocalinkReportCertificateCreation
	/*CertificateRequestID
	  Certificate Request Id

	*/
	CertificateRequestID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post vocalinkreport certificate requests certificate request ID certificate params
func (o *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams) WithTimeout(timeout time.Duration) *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post vocalinkreport certificate requests certificate request ID certificate params
func (o *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post vocalinkreport certificate requests certificate request ID certificate params
func (o *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams) WithContext(ctx context.Context) *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post vocalinkreport certificate requests certificate request ID certificate params
func (o *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post vocalinkreport certificate requests certificate request ID certificate params
func (o *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams) WithHTTPClient(client *http.Client) *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post vocalinkreport certificate requests certificate request ID certificate params
func (o *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCertificateCreationRequest adds the certificateCreationRequest to the post vocalinkreport certificate requests certificate request ID certificate params
func (o *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams) WithCertificateCreationRequest(certificateCreationRequest *models.VocalinkReportCertificateCreation) *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams {
	o.SetCertificateCreationRequest(certificateCreationRequest)
	return o
}

// SetCertificateCreationRequest adds the certificateCreationRequest to the post vocalinkreport certificate requests certificate request ID certificate params
func (o *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams) SetCertificateCreationRequest(certificateCreationRequest *models.VocalinkReportCertificateCreation) {
	o.CertificateCreationRequest = certificateCreationRequest
}

// WithCertificateRequestID adds the certificateRequestID to the post vocalinkreport certificate requests certificate request ID certificate params
func (o *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams) WithCertificateRequestID(certificateRequestID strfmt.UUID) *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams {
	o.SetCertificateRequestID(certificateRequestID)
	return o
}

// SetCertificateRequestID adds the certificateRequestId to the post vocalinkreport certificate requests certificate request ID certificate params
func (o *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams) SetCertificateRequestID(certificateRequestID strfmt.UUID) {
	o.CertificateRequestID = certificateRequestID
}

// WriteToRequest writes these params to a swagger request
func (o *PostVocalinkreportCertificateRequestsCertificateRequestIDCertificateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CertificateCreationRequest != nil {
		if err := r.SetBodyParam(o.CertificateCreationRequest); err != nil {
			return err
		}
	}

	// path param certificate_request_id
	if err := r.SetPathParam("certificate_request_id", o.CertificateRequestID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
