// Code generated by go-swagger; DO NOT EDIT.

package subscriptions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/form3tech-oss/terraform-provider-form3/models"
)

// DeleteSubscriptionsIDReader is a Reader for the DeleteSubscriptionsID structure.
type DeleteSubscriptionsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSubscriptionsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteSubscriptionsIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteSubscriptionsIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteSubscriptionsIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteSubscriptionsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteSubscriptionsIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewDeleteSubscriptionsIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeleteSubscriptionsIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteSubscriptionsIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeleteSubscriptionsIDServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteSubscriptionsIDNoContent creates a DeleteSubscriptionsIDNoContent with default headers values
func NewDeleteSubscriptionsIDNoContent() *DeleteSubscriptionsIDNoContent {
	return &DeleteSubscriptionsIDNoContent{}
}

/* DeleteSubscriptionsIDNoContent describes a response with status code 204, with default header values.

Subscription deleted OK. No body content will be returned
*/
type DeleteSubscriptionsIDNoContent struct {
}

func (o *DeleteSubscriptionsIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{id}][%d] deleteSubscriptionsIdNoContent ", 204)
}

func (o *DeleteSubscriptionsIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSubscriptionsIDBadRequest creates a DeleteSubscriptionsIDBadRequest with default headers values
func NewDeleteSubscriptionsIDBadRequest() *DeleteSubscriptionsIDBadRequest {
	return &DeleteSubscriptionsIDBadRequest{}
}

/* DeleteSubscriptionsIDBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteSubscriptionsIDBadRequest struct {
	Payload *models.APIError
}

func (o *DeleteSubscriptionsIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{id}][%d] deleteSubscriptionsIdBadRequest  %+v", 400, o.Payload)
}
func (o *DeleteSubscriptionsIDBadRequest) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteSubscriptionsIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSubscriptionsIDUnauthorized creates a DeleteSubscriptionsIDUnauthorized with default headers values
func NewDeleteSubscriptionsIDUnauthorized() *DeleteSubscriptionsIDUnauthorized {
	return &DeleteSubscriptionsIDUnauthorized{}
}

/* DeleteSubscriptionsIDUnauthorized describes a response with status code 401, with default header values.

Authentication credentials were missing or incorrect
*/
type DeleteSubscriptionsIDUnauthorized struct {
	Payload *models.APIError
}

func (o *DeleteSubscriptionsIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{id}][%d] deleteSubscriptionsIdUnauthorized  %+v", 401, o.Payload)
}
func (o *DeleteSubscriptionsIDUnauthorized) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteSubscriptionsIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSubscriptionsIDForbidden creates a DeleteSubscriptionsIDForbidden with default headers values
func NewDeleteSubscriptionsIDForbidden() *DeleteSubscriptionsIDForbidden {
	return &DeleteSubscriptionsIDForbidden{}
}

/* DeleteSubscriptionsIDForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteSubscriptionsIDForbidden struct {
	Payload *models.APIError
}

func (o *DeleteSubscriptionsIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{id}][%d] deleteSubscriptionsIdForbidden  %+v", 403, o.Payload)
}
func (o *DeleteSubscriptionsIDForbidden) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteSubscriptionsIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSubscriptionsIDNotFound creates a DeleteSubscriptionsIDNotFound with default headers values
func NewDeleteSubscriptionsIDNotFound() *DeleteSubscriptionsIDNotFound {
	return &DeleteSubscriptionsIDNotFound{}
}

/* DeleteSubscriptionsIDNotFound describes a response with status code 404, with default header values.

Record not found
*/
type DeleteSubscriptionsIDNotFound struct {
	Payload *models.APIError
}

func (o *DeleteSubscriptionsIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{id}][%d] deleteSubscriptionsIdNotFound  %+v", 404, o.Payload)
}
func (o *DeleteSubscriptionsIDNotFound) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteSubscriptionsIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSubscriptionsIDConflict creates a DeleteSubscriptionsIDConflict with default headers values
func NewDeleteSubscriptionsIDConflict() *DeleteSubscriptionsIDConflict {
	return &DeleteSubscriptionsIDConflict{}
}

/* DeleteSubscriptionsIDConflict describes a response with status code 409, with default header values.

Conflict
*/
type DeleteSubscriptionsIDConflict struct {
	Payload *models.APIError
}

func (o *DeleteSubscriptionsIDConflict) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{id}][%d] deleteSubscriptionsIdConflict  %+v", 409, o.Payload)
}
func (o *DeleteSubscriptionsIDConflict) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteSubscriptionsIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSubscriptionsIDTooManyRequests creates a DeleteSubscriptionsIDTooManyRequests with default headers values
func NewDeleteSubscriptionsIDTooManyRequests() *DeleteSubscriptionsIDTooManyRequests {
	return &DeleteSubscriptionsIDTooManyRequests{}
}

/* DeleteSubscriptionsIDTooManyRequests describes a response with status code 429, with default header values.

The request cannot be served due to the application’s rate limit
*/
type DeleteSubscriptionsIDTooManyRequests struct {
	Payload *models.APIError
}

func (o *DeleteSubscriptionsIDTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{id}][%d] deleteSubscriptionsIdTooManyRequests  %+v", 429, o.Payload)
}
func (o *DeleteSubscriptionsIDTooManyRequests) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteSubscriptionsIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSubscriptionsIDInternalServerError creates a DeleteSubscriptionsIDInternalServerError with default headers values
func NewDeleteSubscriptionsIDInternalServerError() *DeleteSubscriptionsIDInternalServerError {
	return &DeleteSubscriptionsIDInternalServerError{}
}

/* DeleteSubscriptionsIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteSubscriptionsIDInternalServerError struct {
	Payload *models.APIError
}

func (o *DeleteSubscriptionsIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{id}][%d] deleteSubscriptionsIdInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteSubscriptionsIDInternalServerError) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteSubscriptionsIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteSubscriptionsIDServiceUnavailable creates a DeleteSubscriptionsIDServiceUnavailable with default headers values
func NewDeleteSubscriptionsIDServiceUnavailable() *DeleteSubscriptionsIDServiceUnavailable {
	return &DeleteSubscriptionsIDServiceUnavailable{}
}

/* DeleteSubscriptionsIDServiceUnavailable describes a response with status code 503, with default header values.

The server is up, but overloaded with requests. Try again later.
*/
type DeleteSubscriptionsIDServiceUnavailable struct {
	Payload *models.APIError
}

func (o *DeleteSubscriptionsIDServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /subscriptions/{id}][%d] deleteSubscriptionsIdServiceUnavailable  %+v", 503, o.Payload)
}
func (o *DeleteSubscriptionsIDServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteSubscriptionsIDServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
