// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteUsersUserIDCredentialsClientIDParams creates a new DeleteUsersUserIDCredentialsClientIDParams object
// with the default values initialized.
func NewDeleteUsersUserIDCredentialsClientIDParams() *DeleteUsersUserIDCredentialsClientIDParams {
	var ()
	return &DeleteUsersUserIDCredentialsClientIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUsersUserIDCredentialsClientIDParamsWithTimeout creates a new DeleteUsersUserIDCredentialsClientIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteUsersUserIDCredentialsClientIDParamsWithTimeout(timeout time.Duration) *DeleteUsersUserIDCredentialsClientIDParams {
	var ()
	return &DeleteUsersUserIDCredentialsClientIDParams{

		timeout: timeout,
	}
}

// NewDeleteUsersUserIDCredentialsClientIDParamsWithContext creates a new DeleteUsersUserIDCredentialsClientIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteUsersUserIDCredentialsClientIDParamsWithContext(ctx context.Context) *DeleteUsersUserIDCredentialsClientIDParams {
	var ()
	return &DeleteUsersUserIDCredentialsClientIDParams{

		Context: ctx,
	}
}

// NewDeleteUsersUserIDCredentialsClientIDParamsWithHTTPClient creates a new DeleteUsersUserIDCredentialsClientIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteUsersUserIDCredentialsClientIDParamsWithHTTPClient(client *http.Client) *DeleteUsersUserIDCredentialsClientIDParams {
	var ()
	return &DeleteUsersUserIDCredentialsClientIDParams{
		HTTPClient: client,
	}
}

/*DeleteUsersUserIDCredentialsClientIDParams contains all the parameters to send to the API endpoint
for the delete users user ID credentials client ID operation typically these are written to a http.Request
*/
type DeleteUsersUserIDCredentialsClientIDParams struct {

	/*ClientID
	  client id

	*/
	ClientID strfmt.UUID
	/*UserID
	  User Id

	*/
	UserID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete users user ID credentials client ID params
func (o *DeleteUsersUserIDCredentialsClientIDParams) WithTimeout(timeout time.Duration) *DeleteUsersUserIDCredentialsClientIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete users user ID credentials client ID params
func (o *DeleteUsersUserIDCredentialsClientIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete users user ID credentials client ID params
func (o *DeleteUsersUserIDCredentialsClientIDParams) WithContext(ctx context.Context) *DeleteUsersUserIDCredentialsClientIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete users user ID credentials client ID params
func (o *DeleteUsersUserIDCredentialsClientIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete users user ID credentials client ID params
func (o *DeleteUsersUserIDCredentialsClientIDParams) WithHTTPClient(client *http.Client) *DeleteUsersUserIDCredentialsClientIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete users user ID credentials client ID params
func (o *DeleteUsersUserIDCredentialsClientIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClientID adds the clientID to the delete users user ID credentials client ID params
func (o *DeleteUsersUserIDCredentialsClientIDParams) WithClientID(clientID strfmt.UUID) *DeleteUsersUserIDCredentialsClientIDParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the delete users user ID credentials client ID params
func (o *DeleteUsersUserIDCredentialsClientIDParams) SetClientID(clientID strfmt.UUID) {
	o.ClientID = clientID
}

// WithUserID adds the userID to the delete users user ID credentials client ID params
func (o *DeleteUsersUserIDCredentialsClientIDParams) WithUserID(userID strfmt.UUID) *DeleteUsersUserIDCredentialsClientIDParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the delete users user ID credentials client ID params
func (o *DeleteUsersUserIDCredentialsClientIDParams) SetUserID(userID strfmt.UUID) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUsersUserIDCredentialsClientIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param client_id
	if err := r.SetPathParam("client_id", o.ClientID.String()); err != nil {
		return err
	}

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
