// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteUsersUserIDCredentialsClientIDReader is a Reader for the DeleteUsersUserIDCredentialsClientID structure.
type DeleteUsersUserIDCredentialsClientIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUsersUserIDCredentialsClientIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteUsersUserIDCredentialsClientIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteUsersUserIDCredentialsClientIDOK creates a DeleteUsersUserIDCredentialsClientIDOK with default headers values
func NewDeleteUsersUserIDCredentialsClientIDOK() *DeleteUsersUserIDCredentialsClientIDOK {
	return &DeleteUsersUserIDCredentialsClientIDOK{}
}

/*DeleteUsersUserIDCredentialsClientIDOK handles this case with default header values.

Credential deleted
*/
type DeleteUsersUserIDCredentialsClientIDOK struct {
}

func (o *DeleteUsersUserIDCredentialsClientIDOK) Error() string {
	return fmt.Sprintf("[DELETE /security/users/{user_id}/credentials/{client_id}][%d] deleteUsersUserIdCredentialsClientIdOK ", 200)
}

func (o *DeleteUsersUserIDCredentialsClientIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
