// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUsersUserIDCredentialsPublicKeyParams creates a new GetUsersUserIDCredentialsPublicKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUsersUserIDCredentialsPublicKeyParams() *GetUsersUserIDCredentialsPublicKeyParams {
	return &GetUsersUserIDCredentialsPublicKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersUserIDCredentialsPublicKeyParamsWithTimeout creates a new GetUsersUserIDCredentialsPublicKeyParams object
// with the ability to set a timeout on a request.
func NewGetUsersUserIDCredentialsPublicKeyParamsWithTimeout(timeout time.Duration) *GetUsersUserIDCredentialsPublicKeyParams {
	return &GetUsersUserIDCredentialsPublicKeyParams{
		timeout: timeout,
	}
}

// NewGetUsersUserIDCredentialsPublicKeyParamsWithContext creates a new GetUsersUserIDCredentialsPublicKeyParams object
// with the ability to set a context for a request.
func NewGetUsersUserIDCredentialsPublicKeyParamsWithContext(ctx context.Context) *GetUsersUserIDCredentialsPublicKeyParams {
	return &GetUsersUserIDCredentialsPublicKeyParams{
		Context: ctx,
	}
}

// NewGetUsersUserIDCredentialsPublicKeyParamsWithHTTPClient creates a new GetUsersUserIDCredentialsPublicKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUsersUserIDCredentialsPublicKeyParamsWithHTTPClient(client *http.Client) *GetUsersUserIDCredentialsPublicKeyParams {
	return &GetUsersUserIDCredentialsPublicKeyParams{
		HTTPClient: client,
	}
}

/* GetUsersUserIDCredentialsPublicKeyParams contains all the parameters to send to the API endpoint
   for the get users user ID credentials public key operation.

   Typically these are written to a http.Request.
*/
type GetUsersUserIDCredentialsPublicKeyParams struct {

	/* UserID.

	   User Id

	   Format: uuid
	*/
	UserID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get users user ID credentials public key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersUserIDCredentialsPublicKeyParams) WithDefaults() *GetUsersUserIDCredentialsPublicKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get users user ID credentials public key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersUserIDCredentialsPublicKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get users user ID credentials public key params
func (o *GetUsersUserIDCredentialsPublicKeyParams) WithTimeout(timeout time.Duration) *GetUsersUserIDCredentialsPublicKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users user ID credentials public key params
func (o *GetUsersUserIDCredentialsPublicKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users user ID credentials public key params
func (o *GetUsersUserIDCredentialsPublicKeyParams) WithContext(ctx context.Context) *GetUsersUserIDCredentialsPublicKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users user ID credentials public key params
func (o *GetUsersUserIDCredentialsPublicKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users user ID credentials public key params
func (o *GetUsersUserIDCredentialsPublicKeyParams) WithHTTPClient(client *http.Client) *GetUsersUserIDCredentialsPublicKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users user ID credentials public key params
func (o *GetUsersUserIDCredentialsPublicKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the get users user ID credentials public key params
func (o *GetUsersUserIDCredentialsPublicKeyParams) WithUserID(userID strfmt.UUID) *GetUsersUserIDCredentialsPublicKeyParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get users user ID credentials public key params
func (o *GetUsersUserIDCredentialsPublicKeyParams) SetUserID(userID strfmt.UUID) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersUserIDCredentialsPublicKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param user_id
	if err := r.SetPathParam("user_id", o.UserID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
