// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteGocardlessIDReader is a Reader for the DeleteGocardlessID structure.
type DeleteGocardlessIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteGocardlessIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteGocardlessIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteGocardlessIDNoContent creates a DeleteGocardlessIDNoContent with default headers values
func NewDeleteGocardlessIDNoContent() *DeleteGocardlessIDNoContent {
	return &DeleteGocardlessIDNoContent{}
}

/*DeleteGocardlessIDNoContent handles this case with default header values.

Association deleted successfully
*/
type DeleteGocardlessIDNoContent struct {
}

func (o *DeleteGocardlessIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /gocardless/{id}][%d] deleteGocardlessIdNoContent ", 204)
}

func (o *DeleteGocardlessIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
