// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/form3tech-oss/terraform-provider-form3/models"
)

// DeleteAccountValidationDataPublisherIDReader is a Reader for the DeleteAccountValidationDataPublisherID structure.
type DeleteAccountValidationDataPublisherIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAccountValidationDataPublisherIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAccountValidationDataPublisherIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAccountValidationDataPublisherIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteAccountValidationDataPublisherIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAccountValidationDataPublisherIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAccountValidationDataPublisherIDNoContent creates a DeleteAccountValidationDataPublisherIDNoContent with default headers values
func NewDeleteAccountValidationDataPublisherIDNoContent() *DeleteAccountValidationDataPublisherIDNoContent {
	return &DeleteAccountValidationDataPublisherIDNoContent{}
}

/*DeleteAccountValidationDataPublisherIDNoContent handles this case with default header values.

Association deleted
*/
type DeleteAccountValidationDataPublisherIDNoContent struct {
}

func (o *DeleteAccountValidationDataPublisherIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /account-validation-data-publisher/{id}][%d] deleteAccountValidationDataPublisherIdNoContent ", 204)
}

func (o *DeleteAccountValidationDataPublisherIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAccountValidationDataPublisherIDBadRequest creates a DeleteAccountValidationDataPublisherIDBadRequest with default headers values
func NewDeleteAccountValidationDataPublisherIDBadRequest() *DeleteAccountValidationDataPublisherIDBadRequest {
	return &DeleteAccountValidationDataPublisherIDBadRequest{}
}

/*DeleteAccountValidationDataPublisherIDBadRequest handles this case with default header values.

Bad Request
*/
type DeleteAccountValidationDataPublisherIDBadRequest struct {
	Payload *models.APIError
}

func (o *DeleteAccountValidationDataPublisherIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /account-validation-data-publisher/{id}][%d] deleteAccountValidationDataPublisherIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteAccountValidationDataPublisherIDBadRequest) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteAccountValidationDataPublisherIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccountValidationDataPublisherIDForbidden creates a DeleteAccountValidationDataPublisherIDForbidden with default headers values
func NewDeleteAccountValidationDataPublisherIDForbidden() *DeleteAccountValidationDataPublisherIDForbidden {
	return &DeleteAccountValidationDataPublisherIDForbidden{}
}

/*DeleteAccountValidationDataPublisherIDForbidden handles this case with default header values.

Forbidden
*/
type DeleteAccountValidationDataPublisherIDForbidden struct {
	Payload *models.APIError
}

func (o *DeleteAccountValidationDataPublisherIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /account-validation-data-publisher/{id}][%d] deleteAccountValidationDataPublisherIdForbidden  %+v", 403, o.Payload)
}

func (o *DeleteAccountValidationDataPublisherIDForbidden) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteAccountValidationDataPublisherIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAccountValidationDataPublisherIDNotFound creates a DeleteAccountValidationDataPublisherIDNotFound with default headers values
func NewDeleteAccountValidationDataPublisherIDNotFound() *DeleteAccountValidationDataPublisherIDNotFound {
	return &DeleteAccountValidationDataPublisherIDNotFound{}
}

/*DeleteAccountValidationDataPublisherIDNotFound handles this case with default header values.

Not Found
*/
type DeleteAccountValidationDataPublisherIDNotFound struct {
	Payload *models.APIError
}

func (o *DeleteAccountValidationDataPublisherIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /account-validation-data-publisher/{id}][%d] deleteAccountValidationDataPublisherIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteAccountValidationDataPublisherIDNotFound) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteAccountValidationDataPublisherIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
