// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteVocalinkreportIDParams creates a new DeleteVocalinkreportIDParams object
// with the default values initialized.
func NewDeleteVocalinkreportIDParams() *DeleteVocalinkreportIDParams {
	var ()
	return &DeleteVocalinkreportIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteVocalinkreportIDParamsWithTimeout creates a new DeleteVocalinkreportIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteVocalinkreportIDParamsWithTimeout(timeout time.Duration) *DeleteVocalinkreportIDParams {
	var ()
	return &DeleteVocalinkreportIDParams{

		timeout: timeout,
	}
}

// NewDeleteVocalinkreportIDParamsWithContext creates a new DeleteVocalinkreportIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteVocalinkreportIDParamsWithContext(ctx context.Context) *DeleteVocalinkreportIDParams {
	var ()
	return &DeleteVocalinkreportIDParams{

		Context: ctx,
	}
}

// NewDeleteVocalinkreportIDParamsWithHTTPClient creates a new DeleteVocalinkreportIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteVocalinkreportIDParamsWithHTTPClient(client *http.Client) *DeleteVocalinkreportIDParams {
	var ()
	return &DeleteVocalinkreportIDParams{
		HTTPClient: client,
	}
}

/*DeleteVocalinkreportIDParams contains all the parameters to send to the API endpoint
for the delete vocalinkreport ID operation typically these are written to a http.Request
*/
type DeleteVocalinkreportIDParams struct {

	/*ID
	  Association Id

	*/
	ID strfmt.UUID
	/*Version
	  Version

	*/
	Version int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete vocalinkreport ID params
func (o *DeleteVocalinkreportIDParams) WithTimeout(timeout time.Duration) *DeleteVocalinkreportIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete vocalinkreport ID params
func (o *DeleteVocalinkreportIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete vocalinkreport ID params
func (o *DeleteVocalinkreportIDParams) WithContext(ctx context.Context) *DeleteVocalinkreportIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete vocalinkreport ID params
func (o *DeleteVocalinkreportIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete vocalinkreport ID params
func (o *DeleteVocalinkreportIDParams) WithHTTPClient(client *http.Client) *DeleteVocalinkreportIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete vocalinkreport ID params
func (o *DeleteVocalinkreportIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete vocalinkreport ID params
func (o *DeleteVocalinkreportIDParams) WithID(id strfmt.UUID) *DeleteVocalinkreportIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete vocalinkreport ID params
func (o *DeleteVocalinkreportIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithVersion adds the version to the delete vocalinkreport ID params
func (o *DeleteVocalinkreportIDParams) WithVersion(version int64) *DeleteVocalinkreportIDParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the delete vocalinkreport ID params
func (o *DeleteVocalinkreportIDParams) SetVersion(version int64) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteVocalinkreportIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	// query param version
	qrVersion := o.Version
	qVersion := swag.FormatInt64(qrVersion)
	if qVersion != "" {
		if err := r.SetQueryParam("version", qVersion); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
