// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/form3tech-oss/terraform-provider-form3/models"
)

// DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDReader is a Reader for the DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationID structure.
type DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNoContent creates a DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNoContent with default headers values
func NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNoContent() *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNoContent {
	return &DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNoContent{}
}

/*DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNoContent handles this case with default header values.

LHV Association agency synchronisation details deleted
*/
type DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNoContent struct {
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /lhv/{associationId}/agency_synchronisation/{agencySynchronisationId}][%d] deleteLhvAssociationIdAgencySynchronisationAgencySynchronisationIdNoContent ", 204)
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDBadRequest creates a DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDBadRequest with default headers values
func NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDBadRequest() *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDBadRequest {
	return &DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDBadRequest{}
}

/*DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDBadRequest handles this case with default header values.

Bad Request
*/
type DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDBadRequest struct {
	Payload *models.APIError
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /lhv/{associationId}/agency_synchronisation/{agencySynchronisationId}][%d] deleteLhvAssociationIdAgencySynchronisationAgencySynchronisationIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDBadRequest) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDUnauthorized creates a DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDUnauthorized with default headers values
func NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDUnauthorized() *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDUnauthorized {
	return &DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDUnauthorized{}
}

/*DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDUnauthorized handles this case with default header values.

Authentication credentials were missing or incorrect
*/
type DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDUnauthorized struct {
	Payload *models.APIError
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /lhv/{associationId}/agency_synchronisation/{agencySynchronisationId}][%d] deleteLhvAssociationIdAgencySynchronisationAgencySynchronisationIdUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDUnauthorized) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDForbidden creates a DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDForbidden with default headers values
func NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDForbidden() *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDForbidden {
	return &DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDForbidden{}
}

/*DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDForbidden handles this case with default header values.

Forbidden
*/
type DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDForbidden struct {
	Payload *models.APIError
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /lhv/{associationId}/agency_synchronisation/{agencySynchronisationId}][%d] deleteLhvAssociationIdAgencySynchronisationAgencySynchronisationIdForbidden  %+v", 403, o.Payload)
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDForbidden) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNotFound creates a DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNotFound with default headers values
func NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNotFound() *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNotFound {
	return &DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNotFound{}
}

/*DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNotFound handles this case with default header values.

Record not found
*/
type DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNotFound struct {
	Payload *models.APIError
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /lhv/{associationId}/agency_synchronisation/{agencySynchronisationId}][%d] deleteLhvAssociationIdAgencySynchronisationAgencySynchronisationIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNotFound) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDConflict creates a DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDConflict with default headers values
func NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDConflict() *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDConflict {
	return &DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDConflict{}
}

/*DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDConflict handles this case with default header values.

Conflict
*/
type DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDConflict struct {
	Payload *models.APIError
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDConflict) Error() string {
	return fmt.Sprintf("[DELETE /lhv/{associationId}/agency_synchronisation/{agencySynchronisationId}][%d] deleteLhvAssociationIdAgencySynchronisationAgencySynchronisationIdConflict  %+v", 409, o.Payload)
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDConflict) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDTooManyRequests creates a DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDTooManyRequests with default headers values
func NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDTooManyRequests() *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDTooManyRequests {
	return &DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDTooManyRequests{}
}

/*DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDTooManyRequests handles this case with default header values.

The request cannot be served due to the application’s rate limit
*/
type DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDTooManyRequests struct {
	Payload *models.APIError
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDTooManyRequests) Error() string {
	return fmt.Sprintf("[DELETE /lhv/{associationId}/agency_synchronisation/{agencySynchronisationId}][%d] deleteLhvAssociationIdAgencySynchronisationAgencySynchronisationIdTooManyRequests  %+v", 429, o.Payload)
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDTooManyRequests) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDInternalServerError creates a DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDInternalServerError with default headers values
func NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDInternalServerError() *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDInternalServerError {
	return &DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDInternalServerError{}
}

/*DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDInternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDInternalServerError struct {
	Payload *models.APIError
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /lhv/{associationId}/agency_synchronisation/{agencySynchronisationId}][%d] deleteLhvAssociationIdAgencySynchronisationAgencySynchronisationIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDInternalServerError) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDServiceUnavailable creates a DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDServiceUnavailable with default headers values
func NewDeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDServiceUnavailable() *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDServiceUnavailable {
	return &DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDServiceUnavailable{}
}

/*DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDServiceUnavailable handles this case with default header values.

The server is up, but overloaded with requests. Try again later.
*/
type DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDServiceUnavailable struct {
	Payload *models.APIError
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDServiceUnavailable) Error() string {
	return fmt.Sprintf("[DELETE /lhv/{associationId}/agency_synchronisation/{agencySynchronisationId}][%d] deleteLhvAssociationIdAgencySynchronisationAgencySynchronisationIdServiceUnavailable  %+v", 503, o.Payload)
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDServiceUnavailable) GetPayload() *models.APIError {
	return o.Payload
}

func (o *DeleteLhvAssociationIDAgencySynchronisationAgencySynchronisationIDServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
