// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSepainstantIDParams creates a new DeleteSepainstantIDParams object
// with the default values initialized.
func NewDeleteSepainstantIDParams() *DeleteSepainstantIDParams {
	var ()
	return &DeleteSepainstantIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSepainstantIDParamsWithTimeout creates a new DeleteSepainstantIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSepainstantIDParamsWithTimeout(timeout time.Duration) *DeleteSepainstantIDParams {
	var ()
	return &DeleteSepainstantIDParams{

		timeout: timeout,
	}
}

// NewDeleteSepainstantIDParamsWithContext creates a new DeleteSepainstantIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSepainstantIDParamsWithContext(ctx context.Context) *DeleteSepainstantIDParams {
	var ()
	return &DeleteSepainstantIDParams{

		Context: ctx,
	}
}

// NewDeleteSepainstantIDParamsWithHTTPClient creates a new DeleteSepainstantIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSepainstantIDParamsWithHTTPClient(client *http.Client) *DeleteSepainstantIDParams {
	var ()
	return &DeleteSepainstantIDParams{
		HTTPClient: client,
	}
}

/*DeleteSepainstantIDParams contains all the parameters to send to the API endpoint
for the delete sepainstant ID operation typically these are written to a http.Request
*/
type DeleteSepainstantIDParams struct {

	/*ID
	  Association Id

	*/
	ID strfmt.UUID
	/*Version
	  Version

	*/
	Version int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete sepainstant ID params
func (o *DeleteSepainstantIDParams) WithTimeout(timeout time.Duration) *DeleteSepainstantIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete sepainstant ID params
func (o *DeleteSepainstantIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete sepainstant ID params
func (o *DeleteSepainstantIDParams) WithContext(ctx context.Context) *DeleteSepainstantIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete sepainstant ID params
func (o *DeleteSepainstantIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete sepainstant ID params
func (o *DeleteSepainstantIDParams) WithHTTPClient(client *http.Client) *DeleteSepainstantIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete sepainstant ID params
func (o *DeleteSepainstantIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete sepainstant ID params
func (o *DeleteSepainstantIDParams) WithID(id strfmt.UUID) *DeleteSepainstantIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete sepainstant ID params
func (o *DeleteSepainstantIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithVersion adds the version to the delete sepainstant ID params
func (o *DeleteSepainstantIDParams) WithVersion(version int64) *DeleteSepainstantIDParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the delete sepainstant ID params
func (o *DeleteSepainstantIDParams) SetVersion(version int64) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSepainstantIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	// query param version
	qrVersion := o.Version
	qVersion := swag.FormatInt64(qrVersion)
	if qVersion != "" {
		if err := r.SetQueryParam("version", qVersion); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
