// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteProductIDParams creates a new DeleteProductIDParams object
// with the default values initialized.
func NewDeleteProductIDParams() *DeleteProductIDParams {
	var ()
	return &DeleteProductIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProductIDParamsWithTimeout creates a new DeleteProductIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteProductIDParamsWithTimeout(timeout time.Duration) *DeleteProductIDParams {
	var ()
	return &DeleteProductIDParams{

		timeout: timeout,
	}
}

// NewDeleteProductIDParamsWithContext creates a new DeleteProductIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteProductIDParamsWithContext(ctx context.Context) *DeleteProductIDParams {
	var ()
	return &DeleteProductIDParams{

		Context: ctx,
	}
}

// NewDeleteProductIDParamsWithHTTPClient creates a new DeleteProductIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteProductIDParamsWithHTTPClient(client *http.Client) *DeleteProductIDParams {
	var ()
	return &DeleteProductIDParams{
		HTTPClient: client,
	}
}

/*DeleteProductIDParams contains all the parameters to send to the API endpoint
for the delete product ID operation typically these are written to a http.Request
*/
type DeleteProductIDParams struct {

	/*ID
	  Association Id

	*/
	ID strfmt.UUID
	/*Version
	  Version

	*/
	Version int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete product ID params
func (o *DeleteProductIDParams) WithTimeout(timeout time.Duration) *DeleteProductIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete product ID params
func (o *DeleteProductIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete product ID params
func (o *DeleteProductIDParams) WithContext(ctx context.Context) *DeleteProductIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete product ID params
func (o *DeleteProductIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete product ID params
func (o *DeleteProductIDParams) WithHTTPClient(client *http.Client) *DeleteProductIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete product ID params
func (o *DeleteProductIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete product ID params
func (o *DeleteProductIDParams) WithID(id strfmt.UUID) *DeleteProductIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete product ID params
func (o *DeleteProductIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithVersion adds the version to the delete product ID params
func (o *DeleteProductIDParams) WithVersion(version int64) *DeleteProductIDParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the delete product ID params
func (o *DeleteProductIDParams) SetVersion(version int64) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProductIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	// query param version
	qrVersion := o.Version
	qVersion := swag.FormatInt64(qrVersion)
	if qVersion != "" {
		if err := r.SetQueryParam("version", qVersion); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
