// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteLhvAssociationIDMasterAccountsMasterAccountIDParams creates a new DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteLhvAssociationIDMasterAccountsMasterAccountIDParams() *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams {
	return &DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLhvAssociationIDMasterAccountsMasterAccountIDParamsWithTimeout creates a new DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams object
// with the ability to set a timeout on a request.
func NewDeleteLhvAssociationIDMasterAccountsMasterAccountIDParamsWithTimeout(timeout time.Duration) *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams {
	return &DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams{
		timeout: timeout,
	}
}

// NewDeleteLhvAssociationIDMasterAccountsMasterAccountIDParamsWithContext creates a new DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams object
// with the ability to set a context for a request.
func NewDeleteLhvAssociationIDMasterAccountsMasterAccountIDParamsWithContext(ctx context.Context) *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams {
	return &DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams{
		Context: ctx,
	}
}

// NewDeleteLhvAssociationIDMasterAccountsMasterAccountIDParamsWithHTTPClient creates a new DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteLhvAssociationIDMasterAccountsMasterAccountIDParamsWithHTTPClient(client *http.Client) *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams {
	return &DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams{
		HTTPClient: client,
	}
}

/* DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams contains all the parameters to send to the API endpoint
   for the delete lhv association ID master accounts master account ID operation.

   Typically these are written to a http.Request.
*/
type DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams struct {

	/* AssociationID.

	   Association Id

	   Format: uuid
	*/
	AssociationID strfmt.UUID

	/* MasterAccountID.

	   Master Account Id

	   Format: uuid
	*/
	MasterAccountID strfmt.UUID

	/* Version.

	   Version
	*/
	Version int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete lhv association ID master accounts master account ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) WithDefaults() *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete lhv association ID master accounts master account ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete lhv association ID master accounts master account ID params
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) WithTimeout(timeout time.Duration) *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete lhv association ID master accounts master account ID params
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete lhv association ID master accounts master account ID params
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) WithContext(ctx context.Context) *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete lhv association ID master accounts master account ID params
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete lhv association ID master accounts master account ID params
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) WithHTTPClient(client *http.Client) *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete lhv association ID master accounts master account ID params
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssociationID adds the associationID to the delete lhv association ID master accounts master account ID params
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) WithAssociationID(associationID strfmt.UUID) *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams {
	o.SetAssociationID(associationID)
	return o
}

// SetAssociationID adds the associationId to the delete lhv association ID master accounts master account ID params
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) SetAssociationID(associationID strfmt.UUID) {
	o.AssociationID = associationID
}

// WithMasterAccountID adds the masterAccountID to the delete lhv association ID master accounts master account ID params
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) WithMasterAccountID(masterAccountID strfmt.UUID) *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams {
	o.SetMasterAccountID(masterAccountID)
	return o
}

// SetMasterAccountID adds the masterAccountId to the delete lhv association ID master accounts master account ID params
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) SetMasterAccountID(masterAccountID strfmt.UUID) {
	o.MasterAccountID = masterAccountID
}

// WithVersion adds the version to the delete lhv association ID master accounts master account ID params
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) WithVersion(version int64) *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the delete lhv association ID master accounts master account ID params
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) SetVersion(version int64) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLhvAssociationIDMasterAccountsMasterAccountIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param associationId
	if err := r.SetPathParam("associationId", o.AssociationID.String()); err != nil {
		return err
	}

	// path param masterAccountId
	if err := r.SetPathParam("masterAccountId", o.MasterAccountID.String()); err != nil {
		return err
	}

	// query param version
	qrVersion := o.Version
	qVersion := swag.FormatInt64(qrVersion)
	if qVersion != "" {

		if err := r.SetQueryParam("version", qVersion); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
