// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteSepaLiquidityIDReader is a Reader for the DeleteSepaLiquidityID structure.
type DeleteSepaLiquidityIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSepaLiquidityIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteSepaLiquidityIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSepaLiquidityIDNoContent creates a DeleteSepaLiquidityIDNoContent with default headers values
func NewDeleteSepaLiquidityIDNoContent() *DeleteSepaLiquidityIDNoContent {
	return &DeleteSepaLiquidityIDNoContent{}
}

/*DeleteSepaLiquidityIDNoContent handles this case with default header values.

Association deleted
*/
type DeleteSepaLiquidityIDNoContent struct {
}

func (o *DeleteSepaLiquidityIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /sepa-liquidity/{id}][%d] deleteSepaLiquidityIdNoContent ", 204)
}

func (o *DeleteSepaLiquidityIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
