// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetProductsIDParams creates a new GetProductsIDParams object
// with the default values initialized.
func NewGetProductsIDParams() *GetProductsIDParams {
	var ()
	return &GetProductsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProductsIDParamsWithTimeout creates a new GetProductsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProductsIDParamsWithTimeout(timeout time.Duration) *GetProductsIDParams {
	var ()
	return &GetProductsIDParams{

		timeout: timeout,
	}
}

// NewGetProductsIDParamsWithContext creates a new GetProductsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProductsIDParamsWithContext(ctx context.Context) *GetProductsIDParams {
	var ()
	return &GetProductsIDParams{

		Context: ctx,
	}
}

// NewGetProductsIDParamsWithHTTPClient creates a new GetProductsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProductsIDParamsWithHTTPClient(client *http.Client) *GetProductsIDParams {
	var ()
	return &GetProductsIDParams{
		HTTPClient: client,
	}
}

/*GetProductsIDParams contains all the parameters to send to the API endpoint
for the get products ID operation typically these are written to a http.Request
*/
type GetProductsIDParams struct {

	/*ID
	  Association Id

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get products ID params
func (o *GetProductsIDParams) WithTimeout(timeout time.Duration) *GetProductsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get products ID params
func (o *GetProductsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get products ID params
func (o *GetProductsIDParams) WithContext(ctx context.Context) *GetProductsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get products ID params
func (o *GetProductsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get products ID params
func (o *GetProductsIDParams) WithHTTPClient(client *http.Client) *GetProductsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get products ID params
func (o *GetProductsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get products ID params
func (o *GetProductsIDParams) WithID(id strfmt.UUID) *GetProductsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get products ID params
func (o *GetProductsIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetProductsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
