// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetReconciliationParams creates a new GetReconciliationParams object
// with the default values initialized.
func NewGetReconciliationParams() *GetReconciliationParams {
	var ()
	return &GetReconciliationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReconciliationParamsWithTimeout creates a new GetReconciliationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReconciliationParamsWithTimeout(timeout time.Duration) *GetReconciliationParams {
	var ()
	return &GetReconciliationParams{

		timeout: timeout,
	}
}

// NewGetReconciliationParamsWithContext creates a new GetReconciliationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReconciliationParamsWithContext(ctx context.Context) *GetReconciliationParams {
	var ()
	return &GetReconciliationParams{

		Context: ctx,
	}
}

// NewGetReconciliationParamsWithHTTPClient creates a new GetReconciliationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReconciliationParamsWithHTTPClient(client *http.Client) *GetReconciliationParams {
	var ()
	return &GetReconciliationParams{
		HTTPClient: client,
	}
}

/*GetReconciliationParams contains all the parameters to send to the API endpoint
for the get reconciliation operation typically these are written to a http.Request
*/
type GetReconciliationParams struct {

	/*FilterOrganisationID
	  Organisation id

	*/
	FilterOrganisationID []strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get reconciliation params
func (o *GetReconciliationParams) WithTimeout(timeout time.Duration) *GetReconciliationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get reconciliation params
func (o *GetReconciliationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get reconciliation params
func (o *GetReconciliationParams) WithContext(ctx context.Context) *GetReconciliationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get reconciliation params
func (o *GetReconciliationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get reconciliation params
func (o *GetReconciliationParams) WithHTTPClient(client *http.Client) *GetReconciliationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get reconciliation params
func (o *GetReconciliationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilterOrganisationID adds the filterOrganisationID to the get reconciliation params
func (o *GetReconciliationParams) WithFilterOrganisationID(filterOrganisationID []strfmt.UUID) *GetReconciliationParams {
	o.SetFilterOrganisationID(filterOrganisationID)
	return o
}

// SetFilterOrganisationID adds the filterOrganisationId to the get reconciliation params
func (o *GetReconciliationParams) SetFilterOrganisationID(filterOrganisationID []strfmt.UUID) {
	o.FilterOrganisationID = filterOrganisationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetReconciliationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	var valuesFilterOrganisationID []string
	for _, v := range o.FilterOrganisationID {
		valuesFilterOrganisationID = append(valuesFilterOrganisationID, v.String())
	}

	joinedFilterOrganisationID := swag.JoinByFormat(valuesFilterOrganisationID, "")
	// query array param filter[organisation_id]
	if err := r.SetQueryParam("filter[organisation_id]", joinedFilterOrganisationID...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
