// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSepareconciliationIDParams creates a new GetSepareconciliationIDParams object
// with the default values initialized.
func NewGetSepareconciliationIDParams() *GetSepareconciliationIDParams {
	var ()
	return &GetSepareconciliationIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSepareconciliationIDParamsWithTimeout creates a new GetSepareconciliationIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSepareconciliationIDParamsWithTimeout(timeout time.Duration) *GetSepareconciliationIDParams {
	var ()
	return &GetSepareconciliationIDParams{

		timeout: timeout,
	}
}

// NewGetSepareconciliationIDParamsWithContext creates a new GetSepareconciliationIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSepareconciliationIDParamsWithContext(ctx context.Context) *GetSepareconciliationIDParams {
	var ()
	return &GetSepareconciliationIDParams{

		Context: ctx,
	}
}

// NewGetSepareconciliationIDParamsWithHTTPClient creates a new GetSepareconciliationIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSepareconciliationIDParamsWithHTTPClient(client *http.Client) *GetSepareconciliationIDParams {
	var ()
	return &GetSepareconciliationIDParams{
		HTTPClient: client,
	}
}

/*GetSepareconciliationIDParams contains all the parameters to send to the API endpoint
for the get separeconciliation ID operation typically these are written to a http.Request
*/
type GetSepareconciliationIDParams struct {

	/*ID
	  Association Id

	*/
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get separeconciliation ID params
func (o *GetSepareconciliationIDParams) WithTimeout(timeout time.Duration) *GetSepareconciliationIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get separeconciliation ID params
func (o *GetSepareconciliationIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get separeconciliation ID params
func (o *GetSepareconciliationIDParams) WithContext(ctx context.Context) *GetSepareconciliationIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get separeconciliation ID params
func (o *GetSepareconciliationIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get separeconciliation ID params
func (o *GetSepareconciliationIDParams) WithHTTPClient(client *http.Client) *GetSepareconciliationIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get separeconciliation ID params
func (o *GetSepareconciliationIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get separeconciliation ID params
func (o *GetSepareconciliationIDParams) WithID(id strfmt.UUID) *GetSepareconciliationIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get separeconciliation ID params
func (o *GetSepareconciliationIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSepareconciliationIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
