// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetSepaddParams creates a new GetSepaddParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSepaddParams() *GetSepaddParams {
	return &GetSepaddParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSepaddParamsWithTimeout creates a new GetSepaddParams object
// with the ability to set a timeout on a request.
func NewGetSepaddParamsWithTimeout(timeout time.Duration) *GetSepaddParams {
	return &GetSepaddParams{
		timeout: timeout,
	}
}

// NewGetSepaddParamsWithContext creates a new GetSepaddParams object
// with the ability to set a context for a request.
func NewGetSepaddParamsWithContext(ctx context.Context) *GetSepaddParams {
	return &GetSepaddParams{
		Context: ctx,
	}
}

// NewGetSepaddParamsWithHTTPClient creates a new GetSepaddParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSepaddParamsWithHTTPClient(client *http.Client) *GetSepaddParams {
	return &GetSepaddParams{
		HTTPClient: client,
	}
}

/* GetSepaddParams contains all the parameters to send to the API endpoint
   for the get sepadd operation.

   Typically these are written to a http.Request.
*/
type GetSepaddParams struct {

	/* FilterOrganisationID.

	   Organisation id
	*/
	FilterOrganisationID []strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get sepadd params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSepaddParams) WithDefaults() *GetSepaddParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get sepadd params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSepaddParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get sepadd params
func (o *GetSepaddParams) WithTimeout(timeout time.Duration) *GetSepaddParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sepadd params
func (o *GetSepaddParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sepadd params
func (o *GetSepaddParams) WithContext(ctx context.Context) *GetSepaddParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sepadd params
func (o *GetSepaddParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sepadd params
func (o *GetSepaddParams) WithHTTPClient(client *http.Client) *GetSepaddParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sepadd params
func (o *GetSepaddParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilterOrganisationID adds the filterOrganisationID to the get sepadd params
func (o *GetSepaddParams) WithFilterOrganisationID(filterOrganisationID []strfmt.UUID) *GetSepaddParams {
	o.SetFilterOrganisationID(filterOrganisationID)
	return o
}

// SetFilterOrganisationID adds the filterOrganisationId to the get sepadd params
func (o *GetSepaddParams) SetFilterOrganisationID(filterOrganisationID []strfmt.UUID) {
	o.FilterOrganisationID = filterOrganisationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSepaddParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.FilterOrganisationID != nil {

		// binding items for filter[organisation_id]
		joinedFilterOrganisationID := o.bindParamFilterOrganisationID(reg)

		// query array param filter[organisation_id]
		if err := r.SetQueryParam("filter[organisation_id]", joinedFilterOrganisationID...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetSepadd binds the parameter filter[organisation_id]
func (o *GetSepaddParams) bindParamFilterOrganisationID(formats strfmt.Registry) []string {
	filterOrganisationIDIR := o.FilterOrganisationID

	var filterOrganisationIDIC []string
	for _, filterOrganisationIDIIR := range filterOrganisationIDIR { // explode []strfmt.UUID

		filterOrganisationIDIIV := filterOrganisationIDIIR.String() // strfmt.UUID as string
		filterOrganisationIDIC = append(filterOrganisationIDIC, filterOrganisationIDIIV)
	}

	// items.CollectionFormat: ""
	filterOrganisationIDIS := swag.JoinByFormat(filterOrganisationIDIC, "")

	return filterOrganisationIDIS
}
