// Code generated by go-swagger; DO NOT EDIT.

package associations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/form3tech-oss/terraform-provider-form3/models"
)

// PostSepaReconciliationReader is a Reader for the PostSepaReconciliation structure.
type PostSepaReconciliationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSepaReconciliationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostSepaReconciliationCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostSepaReconciliationCreated creates a PostSepaReconciliationCreated with default headers values
func NewPostSepaReconciliationCreated() *PostSepaReconciliationCreated {
	return &PostSepaReconciliationCreated{}
}

/*PostSepaReconciliationCreated handles this case with default header values.

creation response
*/
type PostSepaReconciliationCreated struct {
	Payload *models.SepaReconciliationAssociationCreationResponse
}

func (o *PostSepaReconciliationCreated) Error() string {
	return fmt.Sprintf("[POST /sepa-reconciliation][%d] postSepaReconciliationCreated  %+v", 201, o.Payload)
}

func (o *PostSepaReconciliationCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SepaReconciliationAssociationCreationResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
