// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams creates a new GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams object
// with the default values initialized.
func NewGetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams() *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams {
	var ()
	return &GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParamsWithTimeout creates a new GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParamsWithTimeout(timeout time.Duration) *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams {
	var ()
	return &GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams{

		timeout: timeout,
	}
}

// NewGetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParamsWithContext creates a new GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParamsWithContext(ctx context.Context) *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams {
	var ()
	return &GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams{

		Context: ctx,
	}
}

// NewGetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParamsWithHTTPClient creates a new GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParamsWithHTTPClient(client *http.Client) *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams {
	var ()
	return &GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams{
		HTTPClient: client,
	}
}

/*GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams contains all the parameters to send to the API endpoint
for the get payments ID reversals reversal ID admissions admission ID operation typically these are written to a http.Request
*/
type GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams struct {

	/*AdmissionID
	  Admission Id

	*/
	AdmissionID strfmt.UUID
	/*ID
	  Payment Id

	*/
	ID strfmt.UUID
	/*ReversalID
	  Reversal Id

	*/
	ReversalID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get payments ID reversals reversal ID admissions admission ID params
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) WithTimeout(timeout time.Duration) *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get payments ID reversals reversal ID admissions admission ID params
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get payments ID reversals reversal ID admissions admission ID params
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) WithContext(ctx context.Context) *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get payments ID reversals reversal ID admissions admission ID params
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get payments ID reversals reversal ID admissions admission ID params
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) WithHTTPClient(client *http.Client) *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get payments ID reversals reversal ID admissions admission ID params
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAdmissionID adds the admissionID to the get payments ID reversals reversal ID admissions admission ID params
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) WithAdmissionID(admissionID strfmt.UUID) *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams {
	o.SetAdmissionID(admissionID)
	return o
}

// SetAdmissionID adds the admissionId to the get payments ID reversals reversal ID admissions admission ID params
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) SetAdmissionID(admissionID strfmt.UUID) {
	o.AdmissionID = admissionID
}

// WithID adds the id to the get payments ID reversals reversal ID admissions admission ID params
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) WithID(id strfmt.UUID) *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get payments ID reversals reversal ID admissions admission ID params
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithReversalID adds the reversalID to the get payments ID reversals reversal ID admissions admission ID params
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) WithReversalID(reversalID strfmt.UUID) *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams {
	o.SetReversalID(reversalID)
	return o
}

// SetReversalID adds the reversalId to the get payments ID reversals reversal ID admissions admission ID params
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) SetReversalID(reversalID strfmt.UUID) {
	o.ReversalID = reversalID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPaymentsIDReversalsReversalIDAdmissionsAdmissionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param admissionId
	if err := r.SetPathParam("admissionId", o.AdmissionID.String()); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	// path param reversalId
	if err := r.SetPathParam("reversalId", o.ReversalID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
