// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/form3tech-oss/terraform-provider-form3/models"
)

// NewPostPaymentsParams creates a new PostPaymentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostPaymentsParams() *PostPaymentsParams {
	return &PostPaymentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostPaymentsParamsWithTimeout creates a new PostPaymentsParams object
// with the ability to set a timeout on a request.
func NewPostPaymentsParamsWithTimeout(timeout time.Duration) *PostPaymentsParams {
	return &PostPaymentsParams{
		timeout: timeout,
	}
}

// NewPostPaymentsParamsWithContext creates a new PostPaymentsParams object
// with the ability to set a context for a request.
func NewPostPaymentsParamsWithContext(ctx context.Context) *PostPaymentsParams {
	return &PostPaymentsParams{
		Context: ctx,
	}
}

// NewPostPaymentsParamsWithHTTPClient creates a new PostPaymentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostPaymentsParamsWithHTTPClient(client *http.Client) *PostPaymentsParams {
	return &PostPaymentsParams{
		HTTPClient: client,
	}
}

/* PostPaymentsParams contains all the parameters to send to the API endpoint
   for the post payments operation.

   Typically these are written to a http.Request.
*/
type PostPaymentsParams struct {

	// PaymentCreationRequest.
	PaymentCreationRequest *models.PaymentCreation

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post payments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPaymentsParams) WithDefaults() *PostPaymentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post payments params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostPaymentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post payments params
func (o *PostPaymentsParams) WithTimeout(timeout time.Duration) *PostPaymentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post payments params
func (o *PostPaymentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post payments params
func (o *PostPaymentsParams) WithContext(ctx context.Context) *PostPaymentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post payments params
func (o *PostPaymentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post payments params
func (o *PostPaymentsParams) WithHTTPClient(client *http.Client) *PostPaymentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post payments params
func (o *PostPaymentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPaymentCreationRequest adds the paymentCreationRequest to the post payments params
func (o *PostPaymentsParams) WithPaymentCreationRequest(paymentCreationRequest *models.PaymentCreation) *PostPaymentsParams {
	o.SetPaymentCreationRequest(paymentCreationRequest)
	return o
}

// SetPaymentCreationRequest adds the paymentCreationRequest to the post payments params
func (o *PostPaymentsParams) SetPaymentCreationRequest(paymentCreationRequest *models.PaymentCreation) {
	o.PaymentCreationRequest = paymentCreationRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostPaymentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.PaymentCreationRequest != nil {
		if err := r.SetBodyParam(o.PaymentCreationRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
