// Code generated by go-swagger; DO NOT EDIT.

package payments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/form3tech/terraform-provider-form3/models"
)

// NewPostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams creates a new PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams object
// with the default values initialized.
func NewPostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams() *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams {
	var ()
	return &PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParamsWithTimeout creates a new PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParamsWithTimeout(timeout time.Duration) *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams {
	var ()
	return &PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams{

		timeout: timeout,
	}
}

// NewPostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParamsWithContext creates a new PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParamsWithContext(ctx context.Context) *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams {
	var ()
	return &PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams{

		Context: ctx,
	}
}

// NewPostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParamsWithHTTPClient creates a new PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParamsWithHTTPClient(client *http.Client) *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams {
	var ()
	return &PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams{
		HTTPClient: client,
	}
}

/*PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams contains all the parameters to send to the API endpoint
for the post payments ID returns return ID submissions return submission ID validations operation typically these are written to a http.Request
*/
type PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams struct {

	/*ReturnSubmissionValidationRequest*/
	ReturnSubmissionValidationRequest *models.ReturnSubmissionValidationCreation
	/*ID
	  Payment Id

	*/
	ID strfmt.UUID
	/*ReturnID
	  Return Id

	*/
	ReturnID strfmt.UUID
	/*ReturnSubmissionID
	  Return Submission Id

	*/
	ReturnSubmissionID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) WithTimeout(timeout time.Duration) *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) WithContext(ctx context.Context) *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) WithHTTPClient(client *http.Client) *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReturnSubmissionValidationRequest adds the returnSubmissionValidationRequest to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) WithReturnSubmissionValidationRequest(returnSubmissionValidationRequest *models.ReturnSubmissionValidationCreation) *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams {
	o.SetReturnSubmissionValidationRequest(returnSubmissionValidationRequest)
	return o
}

// SetReturnSubmissionValidationRequest adds the returnSubmissionValidationRequest to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) SetReturnSubmissionValidationRequest(returnSubmissionValidationRequest *models.ReturnSubmissionValidationCreation) {
	o.ReturnSubmissionValidationRequest = returnSubmissionValidationRequest
}

// WithID adds the id to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) WithID(id strfmt.UUID) *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithReturnID adds the returnID to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) WithReturnID(returnID strfmt.UUID) *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams {
	o.SetReturnID(returnID)
	return o
}

// SetReturnID adds the returnId to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) SetReturnID(returnID strfmt.UUID) {
	o.ReturnID = returnID
}

// WithReturnSubmissionID adds the returnSubmissionID to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) WithReturnSubmissionID(returnSubmissionID strfmt.UUID) *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams {
	o.SetReturnSubmissionID(returnSubmissionID)
	return o
}

// SetReturnSubmissionID adds the returnSubmissionId to the post payments ID returns return ID submissions return submission ID validations params
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) SetReturnSubmissionID(returnSubmissionID strfmt.UUID) {
	o.ReturnSubmissionID = returnSubmissionID
}

// WriteToRequest writes these params to a swagger request
func (o *PostPaymentsIDReturnsReturnIDSubmissionsReturnSubmissionIDValidationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ReturnSubmissionValidationRequest != nil {
		if err := r.SetBodyParam(o.ReturnSubmissionValidationRequest); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	// path param returnId
	if err := r.SetPathParam("returnId", o.ReturnID.String()); err != nil {
		return err
	}

	// path param returnSubmissionId
	if err := r.SetPathParam("returnSubmissionId", o.ReturnSubmissionID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
