// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteConfigurationsIDParams creates a new DeleteConfigurationsIDParams object
// with the default values initialized.
func NewDeleteConfigurationsIDParams() *DeleteConfigurationsIDParams {
	var ()
	return &DeleteConfigurationsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteConfigurationsIDParamsWithTimeout creates a new DeleteConfigurationsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteConfigurationsIDParamsWithTimeout(timeout time.Duration) *DeleteConfigurationsIDParams {
	var ()
	return &DeleteConfigurationsIDParams{

		timeout: timeout,
	}
}

// NewDeleteConfigurationsIDParamsWithContext creates a new DeleteConfigurationsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteConfigurationsIDParamsWithContext(ctx context.Context) *DeleteConfigurationsIDParams {
	var ()
	return &DeleteConfigurationsIDParams{

		Context: ctx,
	}
}

// NewDeleteConfigurationsIDParamsWithHTTPClient creates a new DeleteConfigurationsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteConfigurationsIDParamsWithHTTPClient(client *http.Client) *DeleteConfigurationsIDParams {
	var ()
	return &DeleteConfigurationsIDParams{
		HTTPClient: client,
	}
}

/*DeleteConfigurationsIDParams contains all the parameters to send to the API endpoint
for the delete configurations ID operation typically these are written to a http.Request
*/
type DeleteConfigurationsIDParams struct {

	/*ID
	  AccountConfiguration Id

	*/
	ID strfmt.UUID
	/*Version
	  Version

	*/
	Version int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete configurations ID params
func (o *DeleteConfigurationsIDParams) WithTimeout(timeout time.Duration) *DeleteConfigurationsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete configurations ID params
func (o *DeleteConfigurationsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete configurations ID params
func (o *DeleteConfigurationsIDParams) WithContext(ctx context.Context) *DeleteConfigurationsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete configurations ID params
func (o *DeleteConfigurationsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete configurations ID params
func (o *DeleteConfigurationsIDParams) WithHTTPClient(client *http.Client) *DeleteConfigurationsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete configurations ID params
func (o *DeleteConfigurationsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete configurations ID params
func (o *DeleteConfigurationsIDParams) WithID(id strfmt.UUID) *DeleteConfigurationsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete configurations ID params
func (o *DeleteConfigurationsIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WithVersion adds the version to the delete configurations ID params
func (o *DeleteConfigurationsIDParams) WithVersion(version int64) *DeleteConfigurationsIDParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the delete configurations ID params
func (o *DeleteConfigurationsIDParams) SetVersion(version int64) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteConfigurationsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	// query param version
	qrVersion := o.Version
	qVersion := swag.FormatInt64(qrVersion)
	if qVersion != "" {
		if err := r.SetQueryParam("version", qVersion); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
