// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/ewilde/go-form3/models"
)

// GetConfigurationsIDReader is a Reader for the GetConfigurationsID structure.
type GetConfigurationsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConfigurationsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetConfigurationsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetConfigurationsIDOK creates a GetConfigurationsIDOK with default headers values
func NewGetConfigurationsIDOK() *GetConfigurationsIDOK {
	return &GetConfigurationsIDOK{}
}

/*GetConfigurationsIDOK handles this case with default header values.

AccountConfiguration details
*/
type GetConfigurationsIDOK struct {
	Payload *models.AccountConfigurationDetailsResponse
}

func (o *GetConfigurationsIDOK) Error() string {
	return fmt.Sprintf("[GET /configurations/{id}][%d] getConfigurationsIdOK  %+v", 200, o.Payload)
}

func (o *GetConfigurationsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountConfigurationDetailsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
