// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Bic8 Settlement BIC
// Example: BARCDEFF
//
// swagger:model Bic8
type Bic8 string

// Validate validates this bic8
func (m Bic8) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Pattern("", "body", string(m), `^[A-Z]{6,6}[A-Z2-9][A-NP-Z0-9]$`); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this bic8 based on context it is used
func (m Bic8) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
