// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GocardlessAssociationPatchAttributes gocardless association patch attributes
//
// swagger:model GocardlessAssociationPatchAttributes
type GocardlessAssociationPatchAttributes struct {

	// schemes
	Schemes []string `json:"schemes"`

	// third party organisation id
	ThirdPartyOrganisationID *string `json:"third_party_organisation_id,omitempty"`
}

// Validate validates this gocardless association patch attributes
func (m *GocardlessAssociationPatchAttributes) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this gocardless association patch attributes based on context it is used
func (m *GocardlessAssociationPatchAttributes) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GocardlessAssociationPatchAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GocardlessAssociationPatchAttributes) UnmarshalBinary(b []byte) error {
	var res GocardlessAssociationPatchAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
