// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LhvAssociationAttributes lhv association attributes
// swagger:model LhvAssociationAttributes
type LhvAssociationAttributes struct {

	// bic
	Bic string `json:"bic,omitempty"`
}

// Validate validates this lhv association attributes
func (m *LhvAssociationAttributes) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LhvAssociationAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LhvAssociationAttributes) UnmarshalBinary(b []byte) error {
	var res LhvAssociationAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
