// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RoleAttributes role attributes
//
// swagger:model RoleAttributes
type RoleAttributes struct {

	// name
	Name string `json:"name,omitempty"`

	// parent role id
	// Format: uuid
	ParentRoleID *strfmt.UUID `json:"parent_role_id,omitempty"`
}

// Validate validates this role attributes
func (m *RoleAttributes) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParentRoleID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RoleAttributes) validateParentRoleID(formats strfmt.Registry) error {

	if swag.IsZero(m.ParentRoleID) { // not required
		return nil
	}

	if err := validate.FormatOf("parent_role_id", "body", "uuid", m.ParentRoleID.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RoleAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RoleAttributes) UnmarshalBinary(b []byte) error {
	var res RoleAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
